name: .NET Build PR Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Notify Discord
        run: |
          STATUS="${{ needs.build.result }}"
          ICON="⚠️"

          if [ "$STATUS" = "success" ]; then
            ICON="✅"
          elif [ "$STATUS" = "failure" ]; then
            ICON="❌"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🔔 PR Build finished with status: ${ICON} ${STATUS} (by Natalie)\"}" \
               https://discord.com/api/webhooks/1414125419610771466/Xkb9ADuwivDV3vwW0fl-pjpA_bSoq7GRFHfhTucFBAsoAx7TFNW7XPGArLLQESICpfvL